name: user_repository
description: "A repo that handles pizzas"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.2
  rxdart: ^0.28.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true